"""Resources: the catalog index, categories, STLC pipeline, stats, every SKILL.md and its files."""

from __future__ import annotations

from collections import Counter
from pathlib import PurePosixPath
from typing import Any

from fastmcp import FastMCP
from fastmcp.exceptions import ResourceError

from tsf_mcp import config
from tsf_mcp.catalog import Catalog, first_sentence
from tsf_mcp.state import StateProvider


def catalog_markdown(catalog: Catalog) -> str:
    """Human-readable catalog, also written to skills/CATALOG.md by `tsf-mcp catalog`."""
    groups = catalog.categories()
    upstream = sum(1 for s in catalog.skills.values() if s.source == "upstream")
    lines = [
        "# Skill Catalog",
        "",
        f"{len(catalog.skills)} skills: {upstream} synced from "
        f"[{config.UPSTREAM_REPO}](https://github.com/{config.UPSTREAM_REPO}/tree/{config.UPSTREAM_REF}/{config.UPSTREAM_PATH}) "
        f"and {len(catalog.skills) - upstream} added locally. Generated by `tsf-mcp catalog`; do not edit by hand.",
        "",
    ]
    ordered = [p for p in config.STLC_PHASES if p in groups] + [label for label in groups if label not in config.STLC_PHASES]
    for label in ordered:
        skills = groups[label]
        heading = f"STLC {config.STLC_PHASES.index(label) + 1}: {label}" if label in config.STLC_PHASES else f"Pack: {label}"
        lines += [f"## {heading} ({len(skills)})", "", "| Skill | What it does | Source |", "|---|---|---|"]
        for s in skills:
            lines.append(f"| [`{s.name}`]({s.rel_dir}/SKILL.md) | {first_sentence(s.description).replace('|', '/').replace(f' {chr(0x2014)} ', ', ').replace(chr(0x2014), '-')} | {s.source} |")
        lines.append("")
    return "\n".join(lines)


def register(mcp: FastMCP, state: StateProvider) -> None:
    @mcp.resource("skills://catalog", name="catalog", mime_type="application/json")
    def catalog_index() -> list[dict[str, Any]]:
        """Every skill with name, category, one-line summary and path."""
        return [s.summary() for s in state().catalog.skills.values()]

    @mcp.resource("skills://catalog.md", name="catalog_markdown", mime_type="text/markdown")
    def catalog_md() -> str:
        """The catalog as a Markdown table per STLC phase and pack."""
        return catalog_markdown(state().catalog)

    @mcp.resource("skills://categories", name="categories", mime_type="application/json")
    def categories() -> dict[str, list[str]]:
        """Skill names grouped by STLC phase and pack."""
        return {label: [s.name for s in items] for label, items in state().catalog.categories().items()}

    @mcp.resource("skills://stlc-pipeline", name="stlc_pipeline", mime_type="text/markdown")
    def stlc_pipeline() -> str:
        """The STLC as an ordered pipeline with the skills for each phase."""
        groups = state().catalog.categories()
        lines = ["# STLC pipeline", "", " -> ".join(config.STLC_PHASES), ""]
        for i, phase in enumerate(config.STLC_PHASES, start=1):
            lines.append(f"## {i}. {phase}")
            lines += [f"- `{s.name}`: {first_sentence(s.description)}" for s in groups.get(phase, [])]
            lines.append("")
        return "\n".join(lines)

    @mcp.resource("skills://stats", name="stats", mime_type="application/json")
    def stats() -> dict[str, Any]:
        """Counts by kind, category and source."""
        skills = list(state().catalog.skills.values())
        return {
            "total_skills": len(skills),
            "by_kind": dict(Counter(s.kind for s in skills)),
            "by_category": dict(Counter(s.category for s in skills)),
            "by_source": dict(Counter(s.source for s in skills)),
        }

    @mcp.resource("skill://{name}", name="skill", mime_type="text/markdown")
    def skill_markdown(name: str) -> str:
        """The full SKILL.md of one skill, e.g. skill://test-plan-generator."""
        skill = state().catalog.get(name)
        if skill is None:
            raise ResourceError(f"No skill named {name!r}.")
        return skill.raw

    @mcp.resource("skill://{name}/files/{path*}", name="skill_file", mime_type="text/plain")
    def skill_file(name: str, path: str) -> str:
        """A supporting file of a skill, e.g. skill://test-plan-generator/files/references/test-plan-template.md."""
        st = state()
        skill = st.catalog.get(name)
        if skill is None:
            raise ResourceError(f"No skill named {name!r}.")
        rel = PurePosixPath(path)
        if rel.is_absolute() or ".." in rel.parts or path not in skill.files:
            raise ResourceError(f"{path!r} is not a supporting file of {name}. Available: {', '.join(skill.files) or 'none'}")
        return (st.catalog.root / skill.rel_dir / path).read_text(encoding="utf-8", errors="replace")[: config.MAX_FILE_CHARS]
